redis:
  enabled: false
  host: localhost
  port: 6379
  username: username
  password: password
  authentication: true
http:
  host: localhost
  port: 5000
  token: none
  domain: false
mongo:
  enabled: false
  host: localhost
  port: 27017
  database: spotify_db
  auth:
    enabled: false
    username: username
    password: password
    loginDatabase: admin