mongo:
  host: localhost
  port: 27017
  #
  username: ''
  password: ''
  #
  authentication: true
  #
  database: database
redis:
  host: localhost
  port: 6379
  username: username
  password: password
  authentication: true
http:
  host: localhost
  port: 5000
  token: none