package invaded.core.database.redis;

public enum JedisAction {

    STAFF_JOIN , STAFF_LEAVE, PUNISHMENT, RANK
    , DISGUISE, UNDISGUISE, BROADCAST, STAFF_CHAT, ADMIN_CHAT,
    REPORT, STAFF_SWITCH, HELPOP, JOIN_SERVER
    , REMOVE_PUNISHMENT, KICK_PLAYER, UPDATE_COLOR;

}
